answers = [
    "refik halit karay",
    "turan oflazoğlu",
    "halide nusret",
    "edip cansever",
    "edip cansever",
    "lamii çelebi",
    "aziz nesin",
    "aziz nesin",
    "cahit külebi",
    "cahit külebi",
    "dertli",
    "hamdullah suphi",
    "sezai karakoç",
    "oktay rıfat",
    "sait faik",
    "alev alatlı",
    "rasim özdeneren",
    "rasim özdeneren",
    "rasim özdeneren",
    "rasim özdeneren",
    "şeref taşlıova",
    "halit ziya",
    "halit ziya",
    "halit ziya",
    "yaşar kemal",
    "yaşar kemal",
    "keçecizade izzet mola",
    "ahmet rasim",
    "ahmet rasim",
    "ahmet rasim",
    "samim kocagöz",
    "nuri pakdil",
    "atilla ilhan",
    "nahid sırrı örik",
    "mehmet rauf",
    "mehmet rauf",
    "mehmet rauf",
    "muallim naci",
    "cenap şahabettin",
    "cenap şahabettin",
    "cenap şahabettin",
    "cenap şahabettin",
    "hüseyin cahit yalçın",
    "ece ayhan",
    "ahmet hamdi",
    "necip fazıl",
    "ahmet mithat",
    "şeyhülislam yahya", 
    "ihsan oktay anar",
    "emin nihat",
    "tahsin nahit",
    "ali ekrem",
    "nurullah genç",
    "ahmet haşim",
    "leyla erbil",
    "nezihe meriç",
    "ahmet şuayip",
    "muallim naci",
    "mahmut makal",
    "samiha ayverdi",
    "direktör ali",
    "göç",
    "celal sahir", 
    "nabi",
    "süleyman nazif",
    "ali canip yöntem",
    "kaygusuz abdal",
    "ahmet kutsi tecer",
    "necip fazıl",
    "ahmet hamdi tanpınar",
    "peyami sefa",
    "hüseyin rahmi gürpınar",
    "hüseyin rahmi gürpınar",
    "hüseyin rahmi gürpınar",
    "halit fahri ozansoy",
    "bilge karasu", 
    "sadri ertem",
    "samim kocagöz",
    "kemal tahir",
    "kemal tahir",
    "kemal tahir",
    "orhan kemal",
    "orhan kemal",
    "fakir baykurt",
    "necati cumalı",
    "necati cumalı",
    "rıfat ılgaz",
    "halikarnas balıkçısı",
    "abbas sayar",
    "kemal bilbaşar",
    "kemal bilbaşar",
    "kemal bilbaşar",
    "talip apaydın",
    "talip apaydın",
    "necip fazıl",
    "ahmet muhip",
    "cahit sıtkı",
    "cahit sıtkı",
    "asaf halet çelebi",
    "fazıl hüsnü",
    "behçet necatigil",
    "sedat umran",
    "özdemir asaf",
    "özdemir asaf",
    "ziya osman saba",
    "ziya osman saba",
    "sabri esat siyavuşgil",
    "yaşar nabi nayır",
    "vasfi mahir",
    "cevdet kudret",
    "kenan hulusi koray",
    "nazım hikmet",
    "ercüment behzat",
    "cahit ırgat",
    "cahit ırgat",
    "ceyhun atıf kansu",
    "ceyhun atıf kansu",
    "attila ilhan",
    "ahmet oktay",
    "ahmet kutsi tecer",
    "kemalettin kamu",
    "arif nihat",
    "orhan şaik gökyay",
    "zeki ömer defne",
    "zeki ömer defne",
    "behçet kemal çağlar",
    "bedri rahmi",
    "orhan veli",
    "melih cevdet",
    "oktay rıfat",
    "turgut uyar",
    "ilhan berk",
    "ilhan berk",
    "cemal süreyya",
    "ülkü tamer",
    "ülkü tamer",
    "cahit zarifoğlu",
    "erdem bayazıt",
    "ilhan geçer",
    "şinasi",
    "şinasi",
    "şinasi",
    "namık kemal",
    "namık kemal",
    "ziya paşa",
    "ziya paşa",
    "ziya paşa",
    "ahmet mithat",
    "ahmet mithat",
    "ahmet mithat",
    "ahmet vefik",
    "şemsettin sami",
    "şemsettin sami",
    "direktör ali",
    "recaizade",
    "recaizade",
    "recaizade",
    "abdulhak hamit tarhan",
    "abdulhak hamit tarhan",
    "abdulhak hamit tarhan",
    "abdulhak hamit tarhan",
    "muallim naci",
    "mizancı murat",
    "samipaşazade sezai",
    "nabizade nazım",
    "fatma aliye",
    "fatma aliye",  
    "ali mümtaz arolat",
    "buket uzuner",
    "orhan asena",
    "refik erduran",
    "ömer seyfettin",
    "ömer seyfettin",
    "ziya gökalp",
    "ziya gökalp",
    "mehmet emin yurdakul",
    "mehmet emin yurdakul",
    "mehmet emin yurdakul",
    "halide edip",
    "mehmet fuat köprülü",
    "mehmet fuat köprülü",
    "refik halit karay",
    "refik halit karay",
    "yahya kemal",
    "yahya kemal",
    "yakup kadri",
    "reşat nuri",
    ] 
console.log(answers)
