answers = [
    "refik halit karay",
    "turan oflazoğlu",
    "halide nusret",
    "edip cansever",
    "lamii çelebi",
    "aziz nesin",
    "cahit külebi",
    "dertli",
    "hamdullah suphi",
    "sezai karakoç",
    "oktay rıfat",
    "sait faik",
    "alev alatlı",
    "rasim özdeneren",
    "şeref taşlıova",
    "halit ziya",
    "yaşar kemal",
    "keçecizade izzet mola",
    "ahmet rasim",
    "samim kocagöz",
    "nuri pakdil",
    "atilla ilhan",
    "nahid sırrı örik",
    "mehmet rauf",
    "muallim naci",
    "cenap şahabettin",
    "hüseyin cahit yalçın",
    "ece ayhan",
    "ahmet hamdi",
    "necip fazıl",
    "ahmet mithat",
    "şeyhülislam yahya", 
    "ihsan oktay anar",
    "emin nihat",
    "tahsin nahit",
    "ali ekrem",
    "nurullah genç",
    "ahmet haşim",
    "leyla erbil",
    "nezihe meriç",
    "ahmet şuayip",
    "muallim naci",
    "mahmut makal",
    "samiha ayverdi",
    "direktör ali",
    "göç",
    "celal sahir", // 47
    "nabi",
    "süleyman nazif",
    "ali canip yöntem",
    "kaygusuz abdal",
    "ahmet kutsi tecer",
    "necip fazıl",
    "ahmet hamdi tanpınar",
    "peyami sefa",
    "hüseyin rahmi gürpınar",
    "halit fahri ozansoy",
    "bilge karasu",
    ] 
console.log(answers)
