answers = [
    "refik halit karay",
    "turan oflazoğlu",
    "halide nusret",
    "edip cansever",
    "ebul gazi bahadır han",
    "lamii çelebi",
    "aziz nesin",
    "cahit külebi",
    "dertli",
    "hamdullah suphi",
    "sezai karakoç",
    "oktay rıfat",
    "sait faik",
    "alev alatlı",
    "rasim özdeneren",
    "şeref taşlıova",
    "halit ziya",
    "yaşar kemal",
    "keçecizade izzet mola",
    "ahmet rasim",
    "samim kocagöz",
    "nuri pakdil",
    "atilla ilhan",
    "nahid sırrı örik",
    "mehmet rauf",
    "muallim naci",
    "cenap şahabettin",
    "hüseyin cahit yalçın",
    "ece ayhan",
    "ahmet hamdi",
    "necip fazıl",
    "ahmet mithat",
    "şeyhülislam yahya", // 33
    ]
    