questions = [
    "sürgün",
    "kösem sultan",
    "git bahar",
    "yerçekimli karanfil, çağırılmayan yakup",
    "vamık-u azra",
    "zübük",
    "adamın biri, yeşeren otlar",
    "şeytan bunun neresinde, mahlası 'lütfi'",
    "dağ yolu",
    "hızırla kırk saat",
    "karga ile tilki",
    "semaver",
    "yaseminler tüter mi hala?",
    "gül yetiştiren adam, denize açılan kapı",
    "yaşayan insan hazinesi",
    "ilk mensur şiir, sanata dair",
    "ölmez otu, sarı sıcak, orta direk",
    "mihreti keşan",
    "şehir mektupları",
    "kalpaklılar, sam amca",
    "kudüs şairi",
    "bela çiçeği, yağmur kaçağı",
    "sönmeyen ateş",
    "halas",
    "şerare, füruzan, köylü kızların şarkısı",
    "tamat, nesr-i harp",
    "hayal içinde",
    "kınar hanımın denizleri, devlet ve tabiat",
    "beş şehir, edebiyata dair makaleler",
    "ağaç dergisi, tohum",
    "tercüman-ı hakikat",
    "tahmis, nigaristan", 
    "puslu kıtalar atlası",
    "müsameretname",
    "adalar şairi, ruh-ı bikayd",
    "kaside-i askeriyye, ruh-ı kemal",
    "yağmur,çiçekler üşümesin",
    "akşam şairi, piyale",
    "tuhaf bir kadın, karanlığın günü",
    "bozbulanık",
    "son yazılar",
    "ilk köy şiiri, köylü kızların şarkısı",
    "ilk köy eseri, bizim köy",
    "mesihpaşa imamı, ibrahim efendi konağı",
    "lehçetül Hakayık",
    "hulin dağı geçiyorsa hangi destan?",
    "beyaz gölgeler", // 47
    "tuhfetül haremeyn",
    "firak-ı ırak",
    "geçtiğim yol",
    "gevhername",
    "koçyiğit köroğlu",
    "kafa kağıdı",
    "bursa'da zaman",
    "sözde kızlar",
    "mürebbiye",
    "aruza veda",
    "troya'da ölüm vardı",
    ]
console.log(questions)
