questions = [
    "sürgün",
    "kösem sultan",
    "git bahar",
    "yerçekimli karanfil, çağırılmayan yakup",
    "vamık-u azra",
    "zübük, yaşar ne yaşar ne yaşamaz",
    "adamın biri, yeşeren otlar",
    "şeytan bunun neresinde, mahlası 'lütfi'",
    "dağ yolu",
    "hızırla kırk saat, monna rosa, diriliş",
    "karga ile tilki",
    "semaver",
    "yaseminler tüter mi hala?",
    "gül yetiştiren adam, denize açılan kapı",
    "yaşayan insan hazinesi",
    "ilk mensur şiir, sanata dair",
    "ölmez otu, sarı sıcak, orta direk",
    "mihreti keşan",
    "şehir mektupları",
    "kalpaklılar, sam amca",
    "kudüs şairi",
    "bela çiçeği, yağmur kaçağı",
    "sönmeyen ateş",
    "halas",
    "şerare, füruzan, köylü kızların şarkısı)",
    "tamat, nesr-i harp",
    "hayal içinde",
    "kınar hanımın denizleri, devlet ve tabiat",
    "beş şehir, edebiyata dair makaleler",
    "ağaç dergisi, tohum",
    "tercüman-ı hakikat",
    "tahmis, nigaristan", 
    "puslu kıtalar atlası",
    "müsameretname",
    "adalar şairi, ruh-ı bikayd",
    "kaside-i askeriyye, ruh-ı kemal",
    "yağmur,çiçekler üşümesin",
    "akşam şairi, piyale",
    "tuhaf bir kadın, karanlığın günü",
    "bozbulanık",
    "son yazılar",
    "ilk köy şiiri, köylü kızların şarkısı",
    "ilk köy eseri, bizim köy",
    "mesihpaşa imamı, ibrahim efendi konağı",
    "lehçetül Hakayık",
    "hulin dağı geçiyorsa hangi destan?",
    "beyaz gölgeler", 
    "tuhfetül haremeyn",
    "firak-ı ırak",
    "geçtiğim yol",
    "gevhername",
    "koçyiğit köroğlu",
    "kafa kağıdı",
    "ne içindeyim zamanın, bursa'da zaman",
    "sözde kızlar",
    "mürebbiye",
    "aruza veda",
    "troya'da ölüm vardı",
    "çıkrıklar durunca, bacayı indir bacayı kaldır",
    "ikinci dünya, eski toprak",
    "göl insanları, sağır dere, yorgun savaşçı",
    "esir şehrin insanları, devlet ana",
    "murtaza, bereketli topraklar üzerinde",
    "devlet kuşu, baba evi, avare yıllar",
    "tırpan, yılanların öcü(ırazca)",
    "tütün zamanı, acı tütün, susuz yaz",
    "çocuklarım, alişim",
    "aganta burina burinata, deniz gurbetçileri",
    "yılkı atı",
    "denizin çağırışı, cemo, yeşil gölge",
    "bozkırda günler, sarı traktör, yarbükü", // 71
    "örümcek ağı, çile, kaldırımlar",
    "fahriye abla, olvido, serenad",
    "otuz beş yaş, memleket isterim",
    "ömrümde sükut, gün eksilmesin penceremden",
    "he, lamelif, om mani padme hum",
    "çocuk ve allah, üç şehitler destanı",
    "evler şairi, kapalı çarşı, gizli sevda",
    "eşyanın şairi, leke eseri",
    "lavinia, dünya kaçtı gözüme",
    "çiçekleri yemeyin, yalnızlık paylaşılmaz",
    "sebil ve güvercinler, geçen zaman",
    "odalar ve sofalar",
    "varlık dergisi, kahramanlar, onar mısra",
    "tunç sesleri, dağların derdi, hayat şarkıları",
    "birinci perde, sokak",
    "bir yudum su, bahar hikayeleri",
    "memleketimden insan manzaraları, 835 satır",
    "S.O.S, kaos",
    "bu şehrin çocukları, rüzgarlarım konuşuyor",
    "bir çocuk bahçesinde, çocuklar gemisi",
    "cebbaroğlu mehemmed, sisler bulvarı",
    "yol üstündeki semender",
    "orda bir köy var, nerdesin",
    "gurbet şairi, bingöl çobanları",
    "bayrak şairi, bir bayrak rüzgar bekliyor",
    "bu vatan kimin, destursuz bağa girenler",
    "denizden çalınmış ülke, ılgaz",
    "onuncu yıl marşı, erciyesten kopan çığ",
    "yaradana mektuplar, karadut",
    "garip, vazgeçemediğim, destan gibi",
    "rahatı kaçan ağaç, telgrafhane",
    "perçemli sokak, yaşayıp ölmek",
    "arz-ı hal, dünyanın en güzel arabistanı",
    "güneşi yakanların selamı, günaydın yeryüzü",
    "üvercinka, sevda sözleri",
    "soğuk otların altında, gök onları yanıltmaz",
    "işaret çocukları, yedi güzel adam",
    "sebep ey, risaleler",
    "büyüyen eller",
    ]
console.log(questions)
