questions = [
    "sürgün",
    "kösem sultan",
    "git bahar",
    "yerçekimli karanfil, çağırılmayan yakup",
    "şecere-i türk",
    "vamık-u azra",
    "zübük",
    "adamın biri, yeşeren otlar",
    "şeytan bunun neresinde, mahlası 'lütfi'",
    "dağ yolu",
    "hızırla kırk saat",
    "karga ile tilki",
    "semaver",
    "yaseminler tüter mi hala?",
    "gül yetiştiren adam, denize açılan kapı",
    "yaşayan insan hazinesi",
    "ilk mensur şiir, sanata dair",
    "ölmez otu, sarı sıcak, orta direk",
    "mihreti keşan",
    "şehir mektupları",
    "kalpaklılar, sam amca",
    "kudüs şairi",
    "bela çiçeği, yağmur kaçağı",
    "sönmeyen ateş",
    "halas",
    "şerare, füruzan",
    "tamat, nesr-i harp",
    "hayal içinde",
    "kınar hanımın denizleri, devlet ve tabiat",
    "beş şehir, edebiyata dair makaleler",
    "ağaç dergisi, tohum",
    "tercüman-ı hakikat",
    "tahmis, nigaristan", //33
    ]
